name: 'ebpa_matrix_no_md5'

on:
  schedule:
    - cron:  '*/30 0-13 * * *'
  workflow_dispatch:
    inputs:
        tags:
          description: 'action'  

jobs:
  shell:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - atp: CND-P
           if_skype: False
           skype_id: 19:655268b00f704dfc8e71592f93d73bd3@thread.skype 19:0f08ab319e7a431c9a013633f11b0c8b@thread.skype
           skype_username : SKYPE_MINE_USERNAME
           skype_password : SKYPE_MINE_PASSWORD
           IF_PLAYWRIGHT: True
           repo_name  : CECNdata/GA-sec
           repo_token : SEC_TOKEN
           gist_id : 9c79632d7ed0dd565e593fb925a0cfe5
           
         - atp: CND-P-DCE
           if_skype: False
           skype_id: 19:655268b00f704dfc8e71592f93d73bd3@thread.skype 19:0f08ab319e7a431c9a013633f11b0c8b@thread.skype
           skype_username : SKYPE_MINE_USERNAME
           skype_password : SKYPE_MINE_PASSWORD
           IF_PLAYWRIGHT: True
           repo_name  : CECNdata/GA-sec
           repo_token : SEC_TOKEN
           gist_id : 9c79632d7ed0dd565e593fb925a0cfe5

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          repository: '${{ matrix.repo_name  }}'
          token:      '${{ secrets[matrix.repo_token]  }}'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          cd Ebpa/instances/${{ matrix.atp }}
          python -m pip install --upgrade pip
          pip install fire
          pip install pipreqs
          pipreqs .
          pip install -r requirements.txt

      - name: Install Playwright
        if: ${{ env.IF_PLAYWRIGHT  == 'True'}}
        run: |
            python -m playwright install
        env:
            IF_PLAYWRIGHT: ${{ matrix.IF_PLAYWRIGHT }}

      - name: run ebpa
        run: |
            cd Ebpa/modules
            python ebpa.py  --atp_name ${{ matrix.atp }}

      - name: zip_download
        id: download
        continue-on-error: true
        run: |
            zip -r attach.zip Ebpa/modules/download/*

      - name: Send mail
        id: retry
        uses: Wandalen/wretry.action@master
        #if: steps.download.outputs.status == 'success'
        if: success()
        with:
          #server_address: smtp.gmail.com
          #server_port: 465
          #server_address: smtp-mail.outlook.com
          #server_port: 587
          action: dawidd6/action-send-mail@v3
          with: |
            server_address: smtp.gmail.com
            server_port: 465
            username : ${{ secrets.GMAIL_USERNAME }}
            password : ${{ secrets.GMAIL_PASSWORD }}
            subject: Actions for [ ${{matrix.atp}} ]
            body: ${{matrix.atp}} just capture new release!
            to: ${{matrix.atp}}@${{secrets.BASE_MAIL}},${{matrix.SKYPE_MINE_USERNAME}}
            from: ${{ secrets.GMAIL_USERNAME }}
            attachments: attach.zip
          attempt_limit: 3
          attempt_delay: 2000
