name: 'test tor'

on:
  workflow_dispatch:
    inputs:
        tags:
          description: 'action'  

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tor test
    steps:
      - uses: tor-actions/setup-tor@main
      - name: test
        run: |
          apt install ipinfo
          ipinfo `curl ifconfig.co`
