name: 'test tor'

on:
  workflow_dispatch:
    inputs:
        tags:
          description: 'action'  

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tor test
    steps:
      - uses: actions/checkout@main
      - run: docker pull dperson/torproxy
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build and Run containers
        run: |
              docker run  -it --name tor -p 8118:8118 -p 9050:9050 -v ${{ github.workspace }}/.github/.torrc:/etc/tor/torrc:ro -d dperson/torproxy 
              timeout 2m bash -c -- 'while [[ `docker logs tor --tail 1 2>&1` != *"Bootstrapped 100"* ]]; do (sleep 5;docker logs tor --tail 1 2>&1);done '
      
      - name: install ipinfo
        run: |
          sudo add-apt-repository ppa:ipinfo/ppa
          sudo apt-get update
          sudo apt-get install ipinfo -y
          
      - name: test
        run: |
          ipinfo `curl ifconfig.co`
          ipinfo `curl  -Lx 127.0.0.1:8118 ifconfig.me`
          
      - name: test default proxy
        run: |
          export proxy="http://127.0.0.1:8118"
          export http_proxy=$proxy
          export https_proxy=$proxy
          export ftp_proxy=$proxy
          export no_proxy="localhost, 127.0.0.1, ::1"
          ipinfo `curl ifconfig.co`
                    
          
