name: 'test tor'

on:
  workflow_dispatch:
    inputs:
        tags:
          description: 'action'  

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tor test
    steps:
      - uses: actions/checkout@main
      - uses: tor-actions/setup-tor@main
        with:
          config-path: ${{ github.workspace }}/.github/.torrc
      
      - name: install ipinfo
        run: |
          sudo add-apt-repository ppa:ipinfo/ppa
          sudo apt-get update
          sudo apt-get install ipinfo -y
          
      - name: test
        run: |
          ipinfo `curl ifconfig.co`
          ipinfo `curl --socks5 127.0.0.1:9050 ifconfig.co`
